### ISSUE TITLE
About image type comparison experiment？

### ISSUE THREAD

**Issue by bushou-yhh** [jhl-Det/CVA-Net#1]
I noticed that the train annotation has
    ** {
            "file_name": "benign/x28f299ceb056964c/000039.png",
            "height": 670,
            "width": 670,
            "id": 40,
            "frame_id": 39,
            "video_id": 1,
            "is_vid_train_frame": true
        },
        {
            "file_name": "benign/x28f299ceb056964c/000040.png",
            "height": 670,
            "width": 670,
            "id": 41,
            "frame_id": 40,
            "video_id": 1,
            "is_vid_train_frame": false
        },**
When you conduct an image type comparison experiment, use all images or just the image when is_vid_train_frame==True?

**Comment by jhl-Det** [comment]
We used all images when conduct the image type comparison experiments.

**Comment by bushou-yhh** [comment]
Thank you for your reply
