### ISSUE TITLE
error in ms_deformable_col2im_cuda: too many resources requested for launch

### ISSUE THREAD

**Issue by 18370636086** [jhl-Det/CVA-Net#11]
When i run "python test.py", there apper with "error in ms_deformable_col2im_cuda: too many resources requested for launch"
I found many ways to solve it ,but failed. Could you give me some useful suggestion. Thank you very much.

**Comment by jhl-Det** [comment]
I checked the original repo and found some issues like this:https://github.com/fundamentalvision/Deformable-DETR/issues/82.
I think this problem is caused by an incompatible with your CUDA version.

**Comment by 18370636086** [comment]
Thanks，I'll try another version later.
