### ISSUE TITLE
About the annotations of this dataset

### ISSUE THREAD

**Issue by YuY-Z** [jhl-Det/CVA-Net#12]
Hi, @jhl-Det, thanks for your great work. I looked some samples in the dataset and found that some samples are highly similar, but they do not belong to the same class. For example, samples in malignant\7a39ab5d4970bf89, benign\x5a1c46ec6377e946, malignant\2390fbea047347b, and benign\x63c9ba1377f35bf6 look almost identical. Whether the annotations of this dataset are carefully checked?

**Comment by jhl-Det** [comment]
I apologize for the mistakes in our dataset. Upon review, I have found that there are several errors that need to be corrected.

**Comment by YuY-Z** [comment]
That's ok, hope to see corrected data.

**Comment by JawadTawhidi** [comment]
Hi, would you please let us know if the corrected dataset is out or not? I want to use your dataset for some academic research work.
