### ISSUE TITLE
Two small confusions about the code in ./models/cva_net.py

### ISSUE THREAD

**Issue by Starleil** [jhl-Det/CVA-Net#13]
Sorry to bother you, my friends. I have two confusions when I learned your code in ./models/cva_net.py, could u plz clear up my confusions? 

1. ./models/cva_net.py Line 322-334: Does this part of the code actually use when the main is running? Does this part of the code actually work? Because I only see 'pred_logits' and 'pred_boxes' in the out (Line 257-260).
2. ./models/cva_net.py Line 506: 'num_classes' is set to 3. I am a little confused about this because the work aims to distinguish between benign and malignant. Maybe 'num_classes=3' includes the special no-object category, benign, and malignant?

Thank you for your patience and I hope to hear from you!

**Comment by jhl-Det** [comment]
I apologize for any confusion we may have caused.

Regarding question 1, please be advised that the code in ./models/cva_net.py Line 322-334 should be deleted. We apologize for not organizing our coding properly.

In response to your second question, you are correct that 'num_classes=3' denotes the special no-object category, benign, and malignant. In our very early experiment, we had some videos in our dataset where no lesion appeared. However, we removed these videos later, and the appropriate value for 'num_classes' should have been changed to 2.

**Comment by Starleil** [comment]
Thanks for your reply ！
