### ISSUE TITLE
Requesting dataset

### ISSUE THREAD

**Issue by Abdelhafiz** [jhl-Det/CVA-Net#22]
Hi

My name is Dina Abdelhafiz a researcher at University of Connecticut, I am requesting your dataset for academic research to be done with my students. 
Here is my email
dina.abdelhafiz@uconn.edu

Thank you in advanced for sharing your dataset.

**Comment by Abdelhafiz** [comment]
Any updates about sending the dataset?
Thank you in advance

**Comment by jhl-Det** [comment]
the download link for dataset has been updated.
