### ISSUE TITLE
sh make.sh problem

### ISSUE THREAD

**Issue by zhaozhao626** [jhl-Det/CVA-Net#6]
hello,sir.
I have a problem when I'm configuring the models, "Compiling CUDA operators ->>> sh ./make.sh" ，apper **“error: unknown file type '.cu' (from '/home/wjz/cva_net/models/ops/src/cuda/ms_deform_attn_cuda.cu')
  ”**
how do  i handle  this? thank you ,sir
![image](https://user-images.githubusercontent.com/82107239/195985012-816a152c-f81e-4c71-813a-d918bf436789.png)

**Comment by jhl-Det** [comment]
You need to check your CUDA version carefully and install the corresponding pytorch and torchvision.
Please refer to https://github.com/fundamentalvision/Deformable-DETR for more details. Our model is built on it.

**Comment by jhl-Det** [comment]
oh！sorry! I made a huge mistake in that I forgot to merge the "dev" branch to "main" branch. The right code is on the branch "dev". But I have already fixed this problem. You can download the code again and train the model.
