### ISSUE TITLE
How much memory is used on one card with 1 batchsize while training the network? 

### ISSUE THREAD

**Issue by imzhangyd** [jhl-Det/CVA-Net#7]
I try to train this network with 1 batchsize on one card of RTX3090 (24GB), but out of memory.

**Comment by jhl-Det** [comment]
You can try to remove the attention module in the network by deleting "--self_attn" in ./configs/config.sh.
I trained this model on Tesla V100 (32GB).

**Comment by leimeng86** [comment]
I also encountered this `RuntimeError: Out of memory`. Without `--self_attn`, after 50-epoch training, the evaluation results on val set are shown in the table below, which is a quite significant performance drop.

| eval | AP | AP50 | AP75 |
| --- | --- | --- | --- |
| after final epoch (50e) | 29.4 | 50.9 | 33.3| 

P.S. my training configuration script (no change to `run_dist_launch.sh`):
```bash
#!/bin/bash

set -x

EXP_DIR=./outputs/train_paper
PY_ARGS=${@:1}

python3 -u main.py \
    --output_dir ${EXP_DIR} \
    --data_mode '15frames' \
    --num_global_frames 3 \
    --num_feature_levels 4 \
    --batch_size 1 \
    --lr 5e-5 \
    --cache_mode \
    --dist_url tcp://127.0.0.1:50001 \
    --shuffled_aug "centerCrop" \
    ${PY_ARGS}
```

**Comment by jhl-Det** [comment]
oh！sorry! I made a huge mistake in that I forgot to merge the "dev" branch to "main" branch. The right code is on the branch "dev". But I have already fixed this problem. You can download the code again and train the model.

**Comment by jhl-Det** [comment]
> 
Here is my memory usage.
<img width="758" alt="gpu-usage" src="https://user-images.githubusercontent.com/107089734/211972944-a0ea65aa-3141-4a9b-87ed-e9de2c35d70e.png">
