### ISSUE TITLE
Cannot download the dataset

### ISSUE THREAD

**Issue by AIDENCHOII** [jhl-Det/CVA-Net#8]
Hi.

I was trying to download the dataset from the link(https://pan.baidu.com/s/1yYME7-DvvIEZzCb72NXaJA?pwd=jnie).
Could you provide me a new link that I can download the dataset?

Thank you.

**Comment by jhl-Det** [comment]
Hi,
Thank you for your attention. I think the link is available; maybe you can check your network. But I will update another way (Google drive) to download the dataset later.
Best regard.

**Comment by LouisDo2108** [comment]
Hi jhl-Det.

I have read your work thoroughly and I am interested in your dataset for academic research purposes. Could you please provide us the approximated time that you would provide the Google Drive link?

Thank you.

**Comment by jhl-Det** [comment]
Hi,
	Sorry for replying you so late, here is Google drive link https://drive.google.com/file/d/1LVXK34OJhC2LkqqyMmVFnXsXQavvZdeF/view?usp=sharing <https://drive.google.com/file/d/1LVXK34OJhC2LkqqyMmVFnXsXQavvZdeF/view?usp=sharing>

Best regard!
