### ISSUE TITLE
Where is the inter-video fusion block and intra-video fusion block ?

### ISSUE THREAD

**Issue by AlfredQin** [jhl-Det/CVA-Net#9]
Hi @jhl-Det ,  thanks for your great work. I try to find the code block for intra-video fusion and inter-video fusion proposed in the paper and it seems that these code blocks are located at the Class Joiner in the backbone.py, I find the implementation are different with the attention operation represented in the paper. Could you tell me where are the code blocks about the fusion module in this repository ? Thank you !

**Comment by leimeng86** [comment]
What I actually found is that inter-video and intra-vide fusion blocks are just average pooling in this codebase [(source code)](https://github.com/jhl-Det/CVA-Net/blob/main/models/backbone.py#L201-L221) instead of attention blocks described in the original paper.
```python
            # inter-video fusion
            for i in range(f // 2):
                x_i = torch.cat(
                    (x.tensors[:, i, :, :, :], 
                     x.tensors[:, i + f // 2, :, :, :]
                     ), 1)
                if c==256:
                    x_i = self.avg_pool256(x_i)
                elif c == 512:
                    x_i = self.avg_pool512(x_i)
                elif c == 1024:
                    x_i = self.avg_pool1024(x_i)
                else:
                    x_i = self.avg_pool2048(x_i)

                xis.append(x_i)

            # intra-video fusion
            xis = torch.stack(xis)
            x.tensors = torch.mean(xis, 0)
            out.append(x)
```

**Comment by jhl-Det** [comment]
oh！sorry! I made a huge mistake in that I forgot to merge the "dev" branch to "main" branch. The right code is on the branch "dev". But I have already fixed this problem. You can download the code again and train the model.

**Comment by leimeng86** [comment]
That's weird. Evaluation on the pretrained model did get consistent results in terms of AP.


model | mAPval0.5:0.95 | weights
-- | -- | --
CVA-Net | 37.5 | [GoogleDrive](https://drive.google.com/file/d/1Wqlh0gBgbzWrXZEcjrPhRqRZ1lmf33iP/view?usp=sharing)


eval | AP | AP50 | AP75
-- | -- | -- | --
pretrained model downloaded from GoogleDrive | 37.5 | 63.2 | 42.3

So, which fusion module has the model been pretrained on, average pooling or attention?
Anyway, it seems like average pooling as fusion blocks works fine, and I will try the updated codebase.

Regards,

**Comment by leimeng86** [comment]
I git-pulled the latest main branch but evaluating the pretrained model downloaded from GoogelDrive on the latest main branch results almost zero AP, by running the following script:

eval | AP | AP50 | AP75
-- | -- | -- | --
the pretrained model | 0.1 | 0.2 | 0.0

```bash
#!/bin/bash

set -xe

EXP_DIR=./outputs/eval_pretrained_02
PY_ARGS=${@:1}

python3 -u main.py \
    --output_dir ${EXP_DIR} \
    --data_mode '15frames' \
    --num_global_frames 3 \
    --num_feature_levels 4 \
    --batch_size 1 \
    --lr 5e-5 \
    --cache_mode \
    --self_attn \
    --dist_url tcp://127.0.0.1:50001 \
    --shuffled_aug "centerCrop" \
    --resume ./outputs/pretrained/cva_net_best_ckpt.pth \
    --eval
    ${PY_ARGS}
```

Regards

**Comment by jhl-Det** [comment]
Oh yes! That's pretty weird. I will check the code carefully later. Let's keep in touch ；）

**Comment by jhl-Det** [comment]
Oh yes! That's pretty weird. I will check the code carefully later. Let's keep in touch ；）

**Comment by jhl-Det** [comment]
Hi there, I am sorry for the problem with the consistency of the codebase. The reason for this is that although this work was published at last year's MICCAI, most of the work we finished was almost two years ago. And we did not organize and save the codebase carefully. And we should have checked the code carefully before released. 
But we have fixed the problem you have encountered. Please download the code and try to train the model again.
I retrained the codebase these days and obtained similar results reported in the paper. The log file is below.
**It is noted worthy** that we trained the model with **Adam** optimizer in the 6~9 epoch and then switched to the **SGD** to finetune. The model would converge better after finetuning. And I am sorry for forgetting to mention this little trick.
[log.txt](https://github.com/jhl-Det/CVA-Net/files/10398032/log.txt)

**Comment by jhl-Det** [comment]
This is my reproduce results.
<img width="736" alt="image" src="https://user-images.githubusercontent.com/107089734/211972528-d2e3c186-2d7b-4e04-aa64-33ad805c06dd.png">
The recods in the paper are:
| AP | AP50 | AP75
| -- | -- | --
| 36.1 | 65.1 | 38.5

**Comment by jhl-Det** [comment]
I am retrained this model using 4  NVIDIA GeForce RTX 3090.
The memory usage is about 24,000M.
<img width="758" alt="gpu-usage" src="https://user-images.githubusercontent.com/107089734/211972807-e2408a6e-1fc6-4537-bdb1-916b7767c184.png">

**Comment by leimeng86** [comment]
I'm still confused.

According to the updated [./configs/config.sh](https://github.com/jhl-Det/CVA-Net/blob/main/configs/config.sh) (also shown below), it first trains 50 epochs ([default `--epochs` setting in main.py](https://github.com/jhl-Det/CVA-Net/blob/main/main.py#L44)) using Adam and then resumes from `./checkpoint.pth` which I assume is the last checkpoint, _i.e. 50-epoch_, from Adam training and trains another 50 epochs.

```bash
#!/usr/bin/env bash

set -x

EXP_DIR=./run/self_attn_final_exp1
PY_ARGS=${@:1}

python3 -u main.py \
    --output_dir ${EXP_DIR} \
    --data_mode '15frames' \
    --num_global_frames 3 \
    --num_feature_levels 4 \
    --batch_size 1 \
    --lr 5e-5 \
    --cache_mode \
    --self_attn \
    --dist_url tcp://127.0.0.1:50001 \
    --shuffled_aug "centerCrop" \
    ${PY_ARGS}
    
# finetune using SGD

python3 -u main.py \
    --output_dir ${EXP_DIR} \
    --data_mode '15frames' \
    --num_global_frames 3 \
    --num_feature_levels 4 \
    --batch_size 1 \
    --lr 5e-5 \
    --self_attn \
    --cache_mode \
    --dist_url tcp://127.0.0.1:50001 \
    --shuffled_aug "centerCrop" \
    --resume ./checkpoint.pth \
    --sgd
    ${PY_ARGS}
```

The training pipeline above is not consistent with the provided [log.txt](https://github.com/jhl-Det/CVA-Net/files/10399323/log.txt) and updated checkpoint file on [GoogleDrive](https://drive.google.com/file/d/1WUBkLAfFZbTTnI7eeNk6iOzgV7AH29GM/view?usp=sharing).
- log.txt shows 8-epoch training using Adam and then 7-epoch training via SGD.
- `checkpoint0013.pth` is the checkpoint after 14-epoch training.

Regrads

**Comment by jhl-Det** [comment]
Yes, I did not set the specific epoch numbers in [./configs/config.sh](https://github.com/jhl-Det/CVA-Net/blob/main/configs/config.sh), I would change the optimizer from Adam to SGD according to my experience.  e.g., when I discovered the model started to converge to a plateau.

**Comment by jhl-Det** [comment]
I updated the checkpoint file is because to ensure consistency with the newly updated codebase.

**Comment by jhl-Det** [comment]
Training this model usually would take about 25 epochs in total.
